name: 'CI - Semantic Search for Images'

on:
  push:
    branches: [ $default-branch ]
    paths: [ 'reference-implementations/semantic-search-for-images/src/**' ]
  pull_request:
    branches: [ $default-branch ]
    paths: [ 'reference-implementations/semantic-search-for-images/src/**' ]
  # Enable manual execution
  workflow_dispatch:

jobs:

  # build-ingestion:

  #   runs-on: ubuntu-latest

  #   defaults:
  #     run:
  #       working-directory: reference-implementations/semantic-search-for-images/src/ingestion

  #   steps:
  #   - uses: actions/checkout@v4
  #   - name: Setup .NET
  #     uses: actions/setup-dotnet@v4
  #     with:
  #       dotnet-version: 8.0.x
  #   - name: Restore dependencies
  #     run: dotnet restore
  #   - name: Build
  #     run: dotnet build --no-restore
  #   - name: Test
  #     run: dotnet test --no-build --verbosity normal

  build-ui-backend:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: reference-implementations/semantic-search-for-images/src/ui-backend

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal

  # build-ui-frontend:

  #   runs-on: ubuntu-latest

  #   defaults:
  #     run:
  #       working-directory: reference-implementations/semantic-search-for-images/src/ui-frontend

  #   steps:
  #   - uses: actions/checkout@v4
  #   - name: Setup Node.js
  #     uses: actions/setup-node@v3
  #     with:
  #       node-version: 20.x
  #       cache: 'npm'
  #   - name: Clean install for dependencies
  #     run: npm ci
  #   - name: Build
  #     run: npm run build --if-present
  #   - name: Test
  #     run: npm test
